# Project: OpenGL
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o stb_image.o
LINKOBJ  = main.o stb_image.o
LIBS     = -L"D:/Dev-IDE/Dev-Cpp/MinGW64/lib" -L"D:/Dev-IDE/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -lopengl32 -lfreeglut -lglu32
INCS     = -I"D:/Dev-IDE/Dev-Cpp/MinGW64/include" -I"D:/Dev-IDE/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-IDE/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Dev-IDE/Dev-Cpp/MinGW64/include" -I"D:/Dev-IDE/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-IDE/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Dev-IDE/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = OpenGL.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

stb_image.o: stb_image.cpp
	$(CPP) -c stb_image.cpp -o stb_image.o $(CXXFLAGS)
